# .graphclientrc.yml
sources:
  - name: youtube-clone
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/adedamolaxl/youtube-clone


documents:
  - ./src/app/queries.query.graphql

